language: python
sudo: false
python:
- '3.6'
install:
- python setup.py install
script:
- true
deploy:
  provider: pypi
  user: sphemakh
  password:
    secure: sQCAY+6fuPuM3M0Pk5uZA3+CQBbqZf2l/8jzMUAubvMs1WeHqEDBbTAz8V0vljKH4/38NRZUrjPw7ajfRUoy6Sc0fLg5skAEWFP+9KKiTaq5UmRhY90f9S2Azbtz++Cr7IO16OMLViEMqiYLJpWXHzuctovUltlDZbBzPZF9gJkVPaxOxGDVnHMDDHP40kfLrZID2IMJ9Eri4NUDklPHtrh6nLE9+pPCpA476KQD0OvYP06c0I8Vm0bU1mPMXFeyl6DopCExqqNhki17GZK/bCua5irlKJlxQIcMJ+6d5emHpxfcGHZJxoqOgUvyv9xgEUfjCwGmXCxAtFMObyWmJzIZ/yCyMZ3hnaL+qhthtAykyop7emDJ06uiJZlq+WimR+TFSt2S29bQMZj/3OBDdnPTz3O34YAXYDdXHveCaw3ZjTsgFvHXrjyhxx2+rz5U/sELj/Xeitpse7mZigG2fsvdt7RNnpdO/rnlYrd2k4v/9b4rA90WAUkOcjhq8CPpxz/1/wdEBYJv4zaAIM8tu5QQiUqvhcFeNOnb5tjhWj+hRLNMnxXyBXVqH5ulCcVF3DwQrVHBsfa/A2VkbeNQyLVOh7q6bRUw/2XKmN7T8Jy+TnfIdTxDuicxfGZf7d/elbdXfZksxDOu0vChorgQvA4MevQEaeD3b5acc7EYSrU=
  on:
    tags: true
    repo: SpheMakh/simms
